FRONTEND_DIR:
  TEMPLATE_DIR: project_store_presentation_layer/templates
  STATIC_DIR: project_store_presentation_layer/static

# KEY_TOKEN:
#   SECRET_KEY: KlgH6AzYDeZeGwD288to79I3vTHT8wp7
#   ALGORITHM: HS256

DATABASE:
  DB_NAME: mysql+pymysql
  HOST: 127.0.0.1
  USER: root
  PORT: 3306
  PASSWORD: gAAAAABiUbDzjIVszVDITh7zPhlglJmnX7-J_PCSeIehsPMQ5_EhHaQP_6w3VNsHtG7gUYWTpHqKg9BXvwj9Tq5MMn14Y277mA==
  DATABASE: projectstore
  # HOST: "sqlite:///./user.db"