FRONTEND_DIR:
  TEMPLATE_DIR: project_store_presentation_layer/templates
  STATIC_DIR: project_store_presentation_layer/static

KEY_TOKEN:
  SECRET_KEY: KlgH6AzYDeZeGwD288to79I3vTHT8wp7
  ALGORITHM: HS256

DATABASE:
  HOST: sqlite:///user.db
  PORT: 3306
  USER: root
  PASSWORD: root
  DATABASE: store